site_name: Hidku Security Playbook
theme:
  name: material
  custom_dir: docs/overrides

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_templates:
  - footer.html
extra_css:
  - 'stylesheets/extra.css'